<Project Sdk="Aspire.AppHost.Sdk/13.2.2">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BaGetter\BaGetter.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Remove="coverlet.collector" />
    <PackageReference Remove="Microsoft.NET.Test.Sdk" />
    <PackageReference Remove="Moq" />
    <PackageReference Remove="xunit" />
    <PackageReference Remove="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
