<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="NuGet.Protocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaGetter.Azure.Aspire.AppHost\BaGetter.Azure.Aspire.AppHost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\BaGetter.Tests\TestData\TestData.1.2.3.nupkg" Link="TestData\TestData.1.2.3.nupkg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
